### ISSUE TITLE
Error "AttributeError:__getattribute__" with extrareader.py

### ISSUE THREAD

**Issue by crscalpone** [barronh/evalwoudc#1]
Hi Barron,

I'm working with GEOS-Chem output, and I have set MODTYP=GCNC in the Makefile. When I run 'make' or 'make ncupdated', the program fails with the following error:

> Traceback (most recent call last):
  File "extract_sondes.py", line 177, in <module>
    tmpf = pncopen(modpaths[0], **modformat, addcf=False)
  File "/home/cscalpon/.local/lib/python3.6/site-packages/PseudoNetCDF/_getreader.py", line 77, in pncopen
    outfile = reader(*args, **kwds)
  File "/aqrun/geos/work/mpe_tools/new_test_evalwoudc/extrareader.py", line 43, in \_\_init\_\_
    self.copyDimension(gds[coordk], key=coordk)
AttributeError: 'GCNC' object has no attribute 'copyDimension'
AttributeError: \_\_getattribute\_\_
Exception ignored in: 'netCDF4.\_netCDF4.Dataset.\_\_dealloc\_\_'
AttributeError: \_\_getattribute\_\_
make: *** [ncupdated] Error 1

I am using python version 3.6.8, PseudoNetCDF version 3.0.2, and netCDF4 version 1.5.2.

I also saw that you explained a similar issue with netCDF4 [here](https://github.com/Unidata/netcdf4-python/issues/788), but I don't know how to apply your solution in this case. 

Thanks,
Cara

**Comment by barronh** [comment]
Cara,

First, try updating to PseudoNetCDF v3.1. I think that will help. evalwoudc was being developed using the misc-dev branch, which has been merged into the new version.

Let me know if you get a new error.

**Comment by crscalpone** [comment]
Switching to PseudoNetCDF v3.1 fixed the error; thanks!
